spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/clientsapis_db?allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: mdymen_pass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

application:
  page-size: 5
