CREATE DATABASE IF NOT EXISTS clientsapis_db;

USE clientsapis_db;

CREATE TABLE IF NOT EXISTS client (

 ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
 CLIENT_ID VARCHAR(100) NOT NULL,
 NAME VARCHAR(100) NOT NULL, 
 AGE INT NOT NULL,
 CREATED TIMESTAMP NOT NULL,
 PRIMARY KEY (ID),
 UNIQUE INDEX (CLIENT_ID),
 INDEX(CLIENT_ID, NAME),
 INDEX(AGE)
);